export const BUSKET_INCREMENT = 'BUSKET_INCREMENT';
export const BUSKET_DECREMENT = 'BUSKET_DECREMENT';
export const LIKES_INCREMENT = 'LIKES_INCREMENT';
export const LIKES_DECREMENT = 'LIKES_DECREMENT';